name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Using Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: "Create env file"
        run: |
          touch variables-production.env
          echo CLIENT_URL=http://devmentor.net >> variables-production.env
          echo PORT=8080 >> variables-production.env
          echo NODE_ENV=production >> variables-production.env
          echo SEND_IN_BLUE_URL=smtp-relay.sendinblue.com >> variables-production.env
          echo SEND_FROM_EMAIL=info@devmentor.net >> variables-production.env
          echo SEND_IN_BLUE_USER=me@ehsangazar.com >> variables-production.env
          echo SEND_IN_BLUE_PASSWORD=${{secrets.SEND_IN_BLUE_PASSWORD}} >> variables-production.env
          echo POSTGRES_DB_DATABSE=devmentor >> variables-production.env
          echo POSTGRES_DB_USER=postgres >> variables-production.env
          echo POSTGRES_DB_PASSWORD=${{secrets.POSTGRES_DB_PASSWORD}} >> variables-production.env
          echo POSTGRES_DB_HOST=devmentor-d.flycast >> variables-production.env
          echo POSTGRES_DB_PORT=5432 >> variables-production.env
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> variables-production.env
          cat variables-production.env

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
